sudo: false
# Use as OS Ubuntu 18.04 (bionic)
dist: bionic

# We should actually not specify a compiler
compiler: gcc

before_install:
- cmake --version

install: 
- mkdir build
- cd build
- cmake .. -DDOWNLOAD_JLINK=OFF -DDOWNLOAD_NRFUTIL=OFF

script:
- VERBOSE=1 make

git:
    depth: 3

# blocklist
branches:
    except:
    - gh-pages
